testServer: false
servername: "HIDE1"
SQL:
  user: "lineal"
  password: "N89RuUAM"
  database: "testdb"
  port: 3306
  host: "localhost"
spawn:
  world: "HIDE_Lobby"
  x: -79.5
  y: 90.5
  z: 61.5
  yaw: 0
  pitch: 0